name: cactus_locator
description: 一个Flutter插件，让应用程序在后台，也可以获得位置更新。在安卓侧集成了 Cactus，提高保活性能。
version: 1.0.1
homepage: https://github.com/kuloud/cactus_locator
issue_tracker: https://github.com/kuloud/cactus_locator/issues
platforms:
  android:
  ios:
#publish_to: https://pub.dartlang.org

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: yukams.app.background_locator
        pluginClass: BackgroundLocatorPlugin
      ios:
        pluginClass: BackgroundLocatorPlugin
