name: cactus_locator
description: A Flutter plugin to request the location even if the app is killed. Sending the location to a dart function in background, also provide a meter filter
version: 1.0.0
homepage: https://github.com/kuloud/background_locator_fixed
issue_tracker: https://github.com/kuloud/background_locator_fixed/issues
platforms:
  android:
  ios:
#publish_to: https://pub.dartlang.org

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: yukams.app.background_locator
        pluginClass: BackgroundLocatorPlugin
      ios:
        pluginClass: BackgroundLocatorPlugin
